apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: grpc-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: sergioferrer9/grpc-client:latest
          env:
            - name: GRPC_SERVER_HOST
              value: "grpc-server"

